* log

** [2023-09-23 Sat 19:43] setting up clasp

did =clasp login=.

On the web, in Project Settings, found SCript ID.

ScriptID: 1NDwTuY_XSv_svkT0Fry3JwHCwS25SPYMfbKBafitzZ-Q-NzLE8MDMf0f

#+begin_quote
clasp clone 1NDwTuY_XSv_svkT0Fry3JwHCwS25SPYMfbKBafitzZ-Q-NzLE8MDMf0f
#+end_quote

init repo

[[https://developers.google.com/apps-script/guides/v8-runtime][Note on supported version of JS]]


** [2023-09-24 Sun 11:29] working with clasp

=clasp pull= seems to just update local from remote.

=clasp push=:
- didn't work at first.
- needed me to enable the Goolge Apps SCript API. DONE.
- now works

Adding comments


** [2024-05-10 Fri 14:41] done

sone: export into importable format, by adding ACTION column with value SKIP to exports

** [2025-08-22 Fri 13:17] Google's docs describe that the .csv native import functionality uses this format:

#+begin_quote
You can import .csv (comma separated values) files into Google Calendar. If you get an error when you import a .csv file, you might be able to fix the formatting.

Open a .csv file or create one with a spreadsheet editor like Google Sheets.

The first row of your new spreadsheet includes headers like “Subject” and “Start Date.” To import into Google Calendar, the headers must be in English. For the correct headers you need to import into Calendar, go to the list below.

Each row below the header row represents an event. For example:

Subject	Start date	Start time
Final exam	05/30/2020	10:00 AM
When you're done, save the file as a .csv file. Then, to import the file into Google Calendar, follow the steps in “Import events into Google Calendar.”

Format headers & events in .csv files
Only the first 2 headers in this list are required. The rest are optional.
Important: The headers must be in English as shown in this article. If any event details have commas (like the location example given), you can include them with quotation marks around the text.

Subject
(Required) The name of the event
Example: Final exam

Start Date
(Required) The first day of the event
Example: 05/30/2020

Start Time
The time the event begins
Example: 10:00 AM

End Date
The last day of the event
Example: 05/30/2020

End Time
The time the event ends
Example: 1:00 PM

All Day Event
Whether the event is an all-day event. 
If it’s an all-day event, enter True. 
If it isn’t an all-day event, enter False.
Example: False

Description
Description or notes about the event
Example: "50 multiple choice questions and two essay questions"

Location
The location for the event
Example: "Columbia, Schermerhorn 614"

Private
Whether the event should be marked private.
If it’s private, enter True.
If it isn’t private, enter False.
Example: True

These examples would create the following event:

Event: "Final exam" on May 30, 2020 10:00 AM–1:00 PM 
Location: "Columbia, Schermerhorn 614" 
Description: "50 multiple choice questions and two essay questions"
Private: Private event
#+end_quote
